name: Build Emscripten on MacOS 13
on: [push]

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Install Emscripten SDK
        uses: mymindstorm/setup-emsdk@v14

      - name: Check Emscripten version
        run: emcc -v

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.30.x'

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: deps fetch dependencies
        run: go run github.com/piot/deps/src/deps@main fetch --dev

      - name: export python path
        run: export EMSDK_PYTHON=`which python3`

      - name: create cmake cache debug using emscripten (emcmake)
        run:
          emcmake cmake -B build/emscripten-debug -DMAKE_WASM_BUILD=ON
          -DCMAKE_BUILD_TYPE=Debug

      - name: create cmake cache release using emscripten (emcmake)
        run: emcmake cmake -B build/emscripten-release -DMAKE_WASM_BUILD=ON

      - name: build debug
        run: cmake --build build/emscripten-debug

      - name: build release
        run: cmake --build build/emscripten-release --clean-first

      - name: build debug again
        run: cmake --build build/emscripten-debug --clean-first

      - uses: actions/upload-artifact@v4
        with:
          name: hexify Emscripten Library
          path: |
            src/lib/libhexify.a
