name: build linux
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install LLVM and Clang 16
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: '17.0.6'
          env: true

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.30.x'

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: deps fetch dependencies
        run:
          go run github.com/piot/deps/src/deps@main fetch

      - name: create cmake cache
        run: cmake -DCMAKE_BUILD_TYPE=Debug .

      - name: build
        run: cmake --build . --clean-first

      - name: test
        run: ctest --verbose

      - uses: actions/upload-artifact@v2
        with:
          name: hexify Linux Library
          path: |
            src/lib/libhexify.a
